# Use an official GCC runtime as a parent image
FROM gcc:latest

# Set the working directory
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY client.cpp .

# Install necessary packages
RUN apt-get update && apt-get install -y \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Compile the client code
RUN g++ -o client client.cpp

# Keep the container running
CMD ["tail", "-f", "/dev/null"]